server:
  port: 8080

spring:
  application:
    name: petcare-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/petcare_db
    username: postgres
    password: teodor123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    # Use a long random secret. For real projects use env vars, not hardcoded nonsense.
    secret: 1234567890123456789012345678901212345678901234567890123456789012
    access-token-minutes: 15
    refresh-token-days: 30
